---
title: "Predicting Ambient Air Pollution (PM2.5) Across the Contiguous U.S."
author: "Aileen Li, Nyah Strickland"
date: "2023-04-18"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(tidymodels)
library(broom)
library(carat)
library(randomForest)
library(plotROC)

origin <- read_csv("https://github.com/rdpeng/stat322E_public/raw/main/data/pm25_data.csv.gz")
```
## Wrangling
```{r Predictors}
## Split origin dataset into 80/20
dat_split <- initial_split(origin, prop =.8)
dat_split

## Use 80% of data for training 
train <- training(dat_split)

# Visualize linear relationship between predictors (lat, lon, state) and predicted value


```

## Models 
```{r Linear Regression}
## Create the recipe
rec <- origin %>% 
    recipe(value ~ lat + lon + state) 
rec

model1 <- linear_reg() %>% 
    set_engine("lm") %>% 
    set_mode("regression")

wf1 <- workflow() %>% 
    add_recipe(rec) %>% 
    add_model(model)
wf1

res <- fit(wf1, data = train)

## Check performance on the complete training data
res %>% 
    extract_fit_engine() %>% 
    summary()

## Check performance using cross-validation
folds <- vfold_cv(train, v = 10)
folds
res <- fit_resamples(wf1, resamples = folds)
res %>% 
    collect_metrics()
```

